### ISSUE TITLE
philosophers use same chopsticks at the same time

### ISSUE THREAD

**Issue by SBester001** [holbein/philosophers-problem#1]
![Problem](https://user-images.githubusercontent.com/38667525/54865944-12e13080-4d6e-11e9-8128-0058ae9a64eb.PNG)

**Comment by victorOle** [comment]
Think I have solved it, by changing the if statement in Tisch.stäbchenNehmen(int nr) to a while statement. That way before a philosopher, ready to be released from the queue, begins his feast it is checked whether both of his chopsticks are actually free. If they aren't he gets to wait another round.
